'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.ITestService")>  _
    Public Interface ITestService
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITestService/Sum", ReplyAction:="http://tempuri.org/ITestService/SumResponse")>  _
        Function Sum(ByVal a As Integer, ByVal b As Integer) As Integer
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ITestService/Sum", ReplyAction:="http://tempuri.org/ITestService/SumResponse")>  _
        Function SumAsync(ByVal a As Integer, ByVal b As Integer) As System.Threading.Tasks.Task(Of Integer)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ITestServiceChannel
        Inherits ServiceReference1.ITestService, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class TestServiceClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.ITestService)
        Implements ServiceReference1.ITestService
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Sum(ByVal a As Integer, ByVal b As Integer) As Integer Implements ServiceReference1.ITestService.Sum
            Return MyBase.Channel.Sum(a, b)
        End Function
        
        Public Function SumAsync(ByVal a As Integer, ByVal b As Integer) As System.Threading.Tasks.Task(Of Integer) Implements ServiceReference1.ITestService.SumAsync
            Return MyBase.Channel.SumAsync(a, b)
        End Function
    End Class
End Namespace
